uw-midsun/firmware_xiv

projects/tutorial_board_button_polling/rules.mk, projects/tutorial_board_button_polling/src/main.c
this is another example project that gets used both for board validation and learning.
=> added a polling gpio example for tutorial board

projects/can_dump/rules.mk, projects/can_dump/scripts/README.md, projects/can_dump/scripts/can_message.py, projects/can_dump/scripts/dump_system.py, projects/can_dump/scripts/parse_data.py, projects/can_dump/scripts/requirements.txt, projects/can_dump/src/main.c
=> [SOFT-19] candump

libraries/ms-common/rules.mk, libraries/ms-common/src/x86/adc.c, libraries/ms-common/test/test_adc.c
Most code copied from the STM version.
=> [SOFT-185] implement x86 adc.c

projects/bms_carrier/inc/bms.h, projects/bms_carrier/inc/bps_heartbeat.h, projects/bms_carrier/inc/can_handler.h, projects/bms_carrier/inc/cell_sense.h, projects/bms_carrier/inc/current_sense.h, projects/bms_carrier/inc/fan_control.h, projects/bms_carrier/inc/passive_balance.h, projects/bms_carrier/inc/relay_control_fsm.h
Design here: https://uwmidsun.atlassian.net/wiki/spaces/ELEC/pages/1290895361/Detailed+Design please review as well. Thanks!
=> [SOFT-202] Add headers / layout for BMS carrier

libraries/ms-drivers/inc/spv1020_mppt.h, libraries/ms-drivers/inc/spv1020_mppt_defs.h, libraries/ms-drivers/src/spv1020_mppt.c, libraries/ms-drivers/src/stm32f0xx/spv1020_mppt.c, libraries/ms-drivers/src/x86/spv1020_mppt.c, libraries/ms-drivers/test/test_spv1020_mppt.c
Supports issuing each command to the SPV1020s and extracting data from the status byte.
Did you know you can have both x86/stm32-specific C files and a common one?
=> [SOFT-188] SPV1020 MPPT driver

projects/power_distribution/src/main.c
Oops: the main event loop wouldn't run.
=> [SOFT-270] Fix power distribution main event loop

Makefile
Quick lint/format wouldn't find any files before this ...
Also included all files that changed from head, so less surprises in travis build 🤞
=> [SOFT-223] Quick Lint/Format Bugfix

projects/solar/inc/data_store.h, projects/solar/inc/logger.h, projects/solar/src/logger.c, projects/solar/test/test_logger.c
It didn't take very long so I went ahead and did the logger module.
If you can think of a good way to test the output let me know.
=> [SOFT-212] Solar logger module

libraries/ms-drivers/src/ads1259_adc.c, projects/bms_carrier/inc/bms.h, projects/bms_carrier/inc/current_sense.h, projects/bms_carrier/inc/fault_bps.h, projects/bms_carrier/rules.mk, projects/bms_carrier/src/bps_heartbeat.c, projects/bms_carrier/src/cell_sense.c, projects/bms_carrier/src/current_sense.c, projects/bms_carrier/src/fault_bps.c, projects/bms_carrier/src/killswitch.c, projects/bms_carrier/src/relay_sequence.c, projects/bms_carrier/test/test_bps_heartbeat.c, projects/bms_carrier/test/test_cell_sense.c, projects/bms_carrier/test/test_current_sense.c, projects/bms_carrier/test/test_fault_bps.c, projects/bms_carrier/test/test_killswitch.c, projects/bms_carrier/test/test_relay_sequence.c, projects/smoke_ads1259/src/main.c
Current sense stores the last 20 readings, and faults
bps in case of overcurrent.
(also I'm dumb and broke the smoke test)
=> [SOFT-172] Implement current sense

libraries/codegen-tooling/inc/can_pack.h, libraries/codegen-tooling/inc/can_transmit.h, libraries/codegen-tooling/inc/can_unpack.h, projects/bms_carrier/inc/bms.h, projects/bms_carrier/inc/can_handler.h, projects/bms_carrier/inc/fan_control.h, projects/bms_carrier/src/can_handler.c, projects/bms_carrier/test/test_can_handler.c
Created can_handler module to tx current, voltage, temperature, relay states and fan states.
=> SOFT 170 can_handler for bms carrier

projects/smoke_thermistor/rules.mk, projects/smoke_thermistor/src/main.c
Created a smoke test that periodically logs raw or converted data from the ADC pins connected to the thermistors.
=> Soft 180 smoke test temp sense

libraries/ms-common/src/x86/adc.c, mpxe/protos/adc.proto, mpxe/protos/stores.proto
=> [SOFT-322] MPXE adc

projects/baby_driver/scripts/test_adc_read.py
Oops, I broke an adc_read Python test last time. This fixes it, and also fixes a couple other things I saw in the test file.
=> [SOFT-306] Fix the adc_read test

libraries/ms-drivers/src/x86/mcp23008_gpio_expander.c, mpxe/integration_tests/deps.mk, mpxe/integration_tests/test_mcp23008.py, mpxe/protos/mcp23008.proto, mpxe/protos/stores.proto, mpxe/sims/ads1259.py, mpxe/sims/mcp23008.py, projects/smoke_mcp23008/src/main.c
=> [Soft-332] mpxe mcp23008 support

README.md
Hopefully saves time for anyone else who had a hard time looking for it.
=> Updated README to include pylint line

.travis.yml, Makefile, README.md, make/filter.mk
Created 2 targets that can run tests from a specified project or run all tests for all projects.
=> Soft 327 integrate python tests

mu/harness/board_sim.py, mu/harness/canio.py, mu/harness/logger.py, mu/harness/pm.py
idk it's kinda messy, comments appreciated
This is so in future we can easily
- toggle logging for pm
- assert on logs maybe??
- serve logs via muctl
=> [SOFT-465] Separate logging in MU

.github/workflows/main.yml, .github/workflows/uncommitted-codegen-changes.md, codegen/can_messages.asciipb
This makes the super weird CI error from https://github.com/uw-midsun/firmware_xiv/pull/348 less weird. If there are uncommitted codegen changes, we post a PR comment and fail early instead of failing to compile mysteriously.
=> [SOFT-473] Check for uncommitted codegen changes in CI

projects/tutorial_board_adc/src/main.c
I noticed a lot of new members making the same mistakes over and over for fw 103 hwk and realized the tutorial_board_adc does not follow our coding standards and is outdated
=> [SOFT-496] Fixed tutorial board adc

projects/pedal_board/inc/brake_data.h
Just adding 5 lines to mark down the values for the parking brake sensor.
=> [SOFT-491] Added parking brake sensor values

libraries/ms-common/inc/can_datagram.h, libraries/ms-common/src/can_datagram.c, libraries/ms-common/test/test_can_datagram.c
if 0 is in a destination_nodes of a datagram, the datagram is received by all
if 0 is the node id, it receives all datagrams
=> SOFT-511 datagram node 0 behaviours

Makefile
Don't think this warrants a whole ticket so decided to create a quick PR
=> updated description of install_requirements

projects/bootloader/inc/config.h, projects/bootloader/src/config.c, projects/bootloader/test/test_config.c
Quick change to config.c for better testability. More detailed update in progress
=> Make config testable

.gitignore, Makefile, make/filter.mk, misra/cppcheckdata.py, misra/misra.py
To use the tool run,
```
make install_misra
```
to install the dependencies and run,
```
make misra PROJECT=X
```
to check compliance for a project
>Note: The MISRA addon for cppcheck was not working for cppcheck 1.82 which is the latest version for our machine. So I copied the scripts and threw them in the misra folder
=> Makefile changes to check MISRA compliance
