projects/smoke_i2c/rules.mk
projects/smoke_i2c/src/main.c

This is more complex than the SPI smoke test since reading and writing are divorced in I2C. I'll create a Confluence page on how to use the smoke test.

[SOFT-182] General I2C smoke test

---

projects/pedal_board/rules.mk

Pedal calib increases test length and is not actually a test, so we shouldn't run it on x86

don't run pedal calib on x86

---

projects/solar/inc/data_store.h
projects/solar/inc/solar_events.h
projects/solar/rules.mk
projects/solar/src/data_store.c
projects/solar/src/main.c
projects/solar/test/test_data_store.c

`data_store` provides an abstraction layer between reading the data and doing something with it. It stores all of the data collected by sense et al., then raises a `DATA_READY_EVENT`. Consumers of the data (`logger`, `fault_monitor`, etc) can retrieve the data directly from `data_store` to avoid overloading the event queue. All data is stored as `uint16_t`.
To store and retrieve data, we use a `DataPoint` enum with one entry for each data point we need (e.g. `DATA_POINT_VOLTAGE_1`, `DATA_POINT_MPPT_CURRENT_3`, etc.).
The `data_store_enter()` function takes a `DataPoint` parameter to identify which data point it is, as well as the data point as a `uint16_t`. It overwrites that data point in the module’s storage.
The `data_store_done()` function will be called by `sense` after a batch of …

[SOFT-206] Implement data_store solar module

---

Makefile
libraries/libcore/inc/log.h
make/build.mk
make/filter.mk
mpxe/harness/rules.mk
mpxe/harness/src/main.c
platform/x86/platform.mk

Adds makefile support for the command 'make mpxe'. We split MPXE into
'pieces', to avoid overalap with 'projects'. Also adds a demo hardcoded
program to run the project can_communication through mpxe, printing its
output.

[SOFT-251] Run something in mpxe

---

projects/solar/inc/solar_config.h
projects/solar/src/main.c
projects/solar/src/solar_config.c
projects/solar/test/test_solar_config.c

This makes solar code complete. 🎉 
I also put `relay_fsm_process_event` at the top of the list of process_event calls so that it gets called first for a miniscule speed boost in opening the relay, though it probably doesn't matter.

[SOFT-303] Integrate data_tx into solar main module

---

projects/power_distribution/src/pd_gpio_config.c

So... power distribution was turning on the horn in the main power up / aux power up / power off sequences. Why? Who knows. In any case, it no longer does that. Instead, the main display is turned on (on in main/aux, off at power off), which was likely omitted as an oversight.

[SOFT-311] Don't turn on horn in startup sequence

---

libraries/ms-common/inc/adc.h
libraries/ms-common/src/stm32f0xx/adc.c
libraries/ms-common/src/x86/adc.c
libraries/ms-common/test/test_adc.c

Alright, back at it with another try. This time, the adcChannel defs are the all the same, and I built on top of the library with Gpio Defs. Will check results of PR check but should be all good. 
Overview of changes:
Adc.h
- Added wrappers for all current functions so that they can be called with gpioAddresses 
- Added compound literal gpioAddresses for adc internal channels (REF, TEMP, BAT)
- Added new Gpio AdcPinCallback typedef to allow funcs with gpios as params to be registered with register_callback_pin func
Adc.c
- Added new static AdcPinInterrupt array to keep track of registered callbacks and readings, ensured that although registered callbacks may exist in either AdcPinInterrupt or AdcInterrupt array, only one can be registered per channel
- Adjusted logic of …

[SOFT-299] Add Gpio abstraction to adc library

---

libraries/ms-common/inc/soft_timer.h
libraries/ms-common/src/stm32f0xx/soft_timer.c
libraries/ms-common/src/x86/soft_timer.c
libraries/ms-common/test/test_soft_timer.c

In `soft_timer.c`, `soft_timer_remaining_time` will segfault when called with an invalid timer ID (anything >= SOFT_TIMER_INVALID_TIMER) since it doesn't perform bounds checking on the `timer_id` passed in, unlike in `soft_timer_cancel`.  
Since we tend to set timer IDs to SOFT_TIMER_INVALID_TIMER after they've finished/been cancelled (ex/ in `bts_7200_current_sense.c`), using `soft_timer_remaining_time` to check if these timers have finished could cause issues, and workarounds will likely complicate the FW.
This PR adds a check for this in the x86 and STM32 implementations of `soft_timer_remaining_time`, as well as a quick test to make sure segfaults don't happen anymore.

[SOFT-340] Check for invalid timer ID in soft_timer_remaining_time

---

projects/solar/inc/pin_defs.h
projects/solar/src/main.c

Rev 2 of solar sense gives us a pin that's high on the 6 MPPT board and low on the 5 MPPT board. This implements checking it.

[SOFT-293] Determine the solar board based on detection pin

---

libraries/ms-common/inc/adc.h
libraries/ms-common/src/stm32f0xx/adc.c

The STM32 version of `adc.c` would return old values from `adc_read_raw` (probably/especially when called form within a soft timer). This is because to block until the ADC reading was ready, we would wait for the EOSEQ (end-of-sequence) bit to change from 1 to 0. However, the EOSEQ bit is always 0 until the end of the sequence, at which point it changes to 1; however, the ADC IRQHandler (interrupt handler) is called whenever EOSEQ changes to 1 and resets it to 0 before the blocking while loop can see the EOSEQ value. Thus, we would just never block, and adding a `!` wouldn't fix it.
The fix is to track whether we're currently converting on our own with a `volatile bool` and wait on that instead.
Also added a notice about not using it from a high-priority interrupt since that'll cause …

[SOFT-347] Fix ADC returning old values on STM32

---

libraries/ms-drivers/inc/mux.h
libraries/ms-drivers/src/mux.c
libraries/ms-drivers/test/test_mux.c
projects/power_distribution/inc/current_measurement.h
projects/power_distribution/src/current_measurement.c
projects/power_distribution/src/current_measurement_config.c
projects/power_distribution/test/test_current_measurement.c
projects/smoke_bts7200/inc/current_measurement_config.h
projects/smoke_bts7200/src/current_measurement_config.c
projects/smoke_bts7200/src/main.c
projects/smoke_spv1020/src/main.c
projects/solar/src/mppt.c

This just moves ownership of real muxes' enable and output pins from the `mux` driver to the individual project. `mux` is a generic driver whose only function is to write a binary number into GPIO pins. In solar, it was used for a demux which didn't even have enable or output pins, so they had no business being in the driver's control.
This also solves the part of the BTS7200 smoke test issue where the mux enable pin was wrongly high instead of low - power_distribution's `current_measurement` takes care of that now, as does `smoke_bts7200`.
I also took the liberty to incorporate a few of the changes from soft_151_power_distro_validation, so smoke_bts7200 should have half a chance of working now.

[SOFT-350] Improve the mux driver

---

libraries/ms-drivers/inc/bts7040_load_switch.h
libraries/ms-drivers/inc/bts7200_load_switch.h
libraries/ms-drivers/src/bts7040_load_switch.c
libraries/ms-drivers/src/bts7200_load_switch.c
libraries/ms-drivers/test/test_bts7040_load_switch.c
libraries/ms-drivers/test/test_bts7200_load_switch.c

It appears that there's a small chance that bts7200_stop and bts7040_stop will return false even if the measurement timer is active when they're called.  This has caused Travis CI to unexpectedly fail a few times.
Since we don't use the return value of these functions anywhere in the codebase, and it doesn't seem likely that we will in future, this changes them to void functions to avoid any issues with this, and changes the test sequence correspondingly so we (hopefully) don't have random failures anymore.

[SOFT-323] Fix issues with bts7200_stop and bts7040_stop

---

libraries/ms-common/test/test_adc.c
projects/baby_driver/inc/adc_read.h
projects/baby_driver/scripts/adc_read.py
projects/baby_driver/src/dispatcher.c
projects/baby_driver/src/main.c

Bugfixes:
* `adc` wasn't initialized in firmware, causing weird readings
* fixed a couple mixups in message IDs in Python, now C and Python are compatible
* added a guard in dispatcher to avoid possible segfaults when a babydriver message is received which doesn't have a callback registered
Quality of life improvement: in the Python `adc_read` function, `raw` now defaults to False, meaning a converted read is the default.

[SOFT-306] Babydriver: minor adc_read compatibility fixes

---

projects/centre_console/src/button_press.c

Tiny change: the button pins are changing for centre console's latest rev. This updates them.

[SOFT-386] Update centre console button pins to latest rev

---

projects/baby_driver/scripts/can_util.py

An interesting bug that popped up when testing x86 `wait()`: when the Python side expects two or more messages from the C side in sequence, sometimes the time it takes to process the first message and start listening for the second one can actually exceed the time it takes to send the second CAN message from the C side (which can be as low as ~400us)! This causes missed messages and broken transactions.
The fix is to use python-can's `BufferedReader` listener, which puts all messages into a queue, or buffer, so that we don't miss any messages. Because we need to catch all messages, even when `next_message` isn't called, I decided to cache the bus/reader (and the required `Notifier` which makes it work) so that there's only one per channel running all the time.

[SOFT-405] Fix Babydriver's next_message skipping messages when the C side is too fast

---

libraries/libcore/inc/test_helpers.h
libraries/libcore/test/test_parameterized.c
libraries/unity/auto/generate_test_runner.rb
make/build_test.mk

Our testing framework Unity gives us a way to use parameterized tests! See test_parameterized.c for an example. (Apparently it breaks github syntax highlighting though, oh well.)
Highlights:
* `TEST_CASE` macro required for it to work defined in test_helpers.h
* parameterized tests enabled with a flag to the test runner generator script in the makefile
* example in test_parameterized.c
* monkey patch to the test runner generator script to remove `(RUN_TEST_NO_ARGS)` spam in the test logs

[SOFT-419] Enable parameterized tests

---

.gitignore

.project is an auto-generated file for project descriptions

.project (auto-generated Eclipse IDE file) added to .gitignore

---

libraries/libcore/inc/status.h
libraries/libcore/test/test_status.c

See Ticket: https://uwmidsun.atlassian.net/browse/SOFT-422
Implemented statement expression to set function return to a variable, and return that variable if not equal to `STATUS_CODE_OK` (0).
A test has been added as well.

SOFT 422: Fix status_ok_or_return to only evaluate argument once

---

libraries/ms-common/src/watchdog.c
libraries/ms-common/test/test_watchdog.c

The `watchdog` library wasn't setting the `timer_id` to `SOFT_TIMER_INVALID_TIMER` before calling `watchdog_kick` which cancels the timer with id `timer_id`, so if we're unlucky, the default `timer_id` would be a valid timer id used by some other soft timer which would get cancelled, causing *super* hard to debug issues. This appeared when trying to debug babydriver.
Fixed by setting the timer ID in `watchdog_start`. Also changed all the empty parameter lists in test_watchdog.c to `(void)` instead of `()` to comply with conventions.

[SOFT-440] Fix watchdog cancelling random soft timers

---

libraries/ms-common/src/x86/can_hw.c
libraries/ms-common/test/test_can.c

On x86, the flow for receiving a CAN message is the following:
1. The RX thread (`prv_rx_thread` in can_hw.c) reads a CAN frame from the socket.
2. The RX thread calls a handler, which turns out to be `prv_rx_handler` in can.c.
3. `prv_rx_handler` calls `can_hw_receive` until it returns false. On x86, `can_hw_receive` will only rx one message (the most recently rx'd one), but it does this to support STM32 which can receive multiple in a row.
4. On the first call, `can_hw_receive` sees that it has a valid frame received, passes the data upwards, resets it, and returns true; on the second call, it sees that it doesn't have a valid frame and returns false.
Previously, we determined whether the frame was valid by assuming that a CAN arbitration ID of 0 would never happen, so the zero ID …

[SOFT-447] Patch x86 CAN library to allow a message with a zero CAN ID

---

libraries/libcore/inc/log.h
libraries/mpxe-store/inc/store.h
libraries/mpxe-store/src/store.c
mpxe/harness/pm.py
mpxe/harness/project.py
mpxe/protos/stores.proto

This had to happen eventually.
Rather than have one pipe for log output and one pipe for protobuf output, I want to unify these into a single pipe and wrap everything in a wrapper message. The naming is currently a bit off (since everything gets exported in a `MxStoreInfo`), but this makes it easier to extend the IO to C: add a new message type, then have separate handling logic for that message type.
Although this is a general improvement, it was originally intended to simplify the implementation of startup conditions.
In log.h, rather than printing and flushing stdout, we print to a buffer, then call some custom logic in store.c to package it into an `MxStoreInfo` and export it via the normal `store_export` logic. We now set a buffer size of 256 characters for logging, but terminals are …

Soft 345 unify mpxe pipes

---

.github/workflows/main.yml

Since there is only one job, I thought a default timeout of 12 minutes would be good enough.

added a timeout of 12 minutes on main.yml file for github wokflow

---

libraries/ms-helper/inc/can_tx_retry_wrapper.h
libraries/ms-helper/src/can_tx_retry_wrapper.c

The module `can_tx_retry_wrapper` is inherently broken for (at least) two reasons:
1. Upon receiving the maximum number of failures it resets its internal statistics (i.e. retry count), but leaves the ghost ack live in the queue to time out later. At best this is a gracefully handled unpleasant surprise, but at worst this re-triggers the retry logic and broadcasts unwanted messages.
2. If anyone were to employ this with an `ack_bitset` of more than one device, an ack from one device would leave `num_remaining` non-zero and cause a retry to all devices, potentially causing difficult side effects
This PR solves both these issues by:
1. Cancelling the ack no matter what the status was after the maximum number of errors are received
2. Properly warning module users of its limitations with an …

[SOFT-233] Always return OK from retrying to avoid leftover acks

---

libraries/ms-common/src/x86/can_hw.c
libraries/ms-common/test/test_can.c
libraries/ms-common/test/test_can_hw.c
projects/baby_driver/test/test_spi_exchange.c

This PR aims to shortcut socketcan when CAN is configured in loopback mode. We want to do this because there's an unfortunately long delay between when a message is TXed and RXed over socketcan, sometimes on the order of hundreds of milliseconds. This issue is exacerbated by the 3 thread model we use for CAN, in which the TX thread can take a while to wake up before TXing a message, leading to an even longer delay.
Some tests rely on CAN delay being deterministic, and occasionally fail when a message takes too long. This causes much grief and hurts developer velocity.
As much as I wanted this to be a clean change in just can_hw.c, some tests relied on CAN taking a non-zero amount of time to process a message. I believe this reliance is incorrect, since it causes non-determinism and …

[SOFT-233] Unflake CAN and some tests

---

libraries/ms-common/src/x86/soft_timer.c
libraries/ms-common/test/test_adc.c
libraries/ms-common/test/test_can.c
libraries/ms-common/test/test_can_ack.c
libraries/ms-common/test/test_can_hw.c
libraries/ms-common/test/test_soft_timer.c
libraries/ms-drivers/test/test_bts7040_load_switch.c
libraries/ms-drivers/test/test_bts7200_load_switch.c

For the soft timers, this changes the implementation from array-based individual timers to list-based backed by a single timer, similar to how the stm32 version works.
Some tests still struggled. I found that busy-looping would occasionally miss timer events, but adding a `wait()` seemed to help. This seems worth having regardless of whether it helps consistency or not, so I threw a bunch of waits around.

[SOFT-233] Deterministic soft timers

---

libraries/libcore/inc/bug.h
projects/power_distribution/src/main.c

In https://github.com/uw-midsun/firmware_xiv/pull/330 I added a `VERIFY_INIT` macro to make the PD main nicer, and Jess suggested it would be good as a libcore module. So here it is.
`BUG` wraps a call and `LOG_CRITICAL`s something like this when the call returns non-OK:
```
[2] projects/power_distribution/src/main.c:153:
****************** BUG TRIGGERED, ABORTING PROGRAM ******************
This indicates initialization failure or another unrecoverable fault.
Call returned status code 2:
current_measurement_init(&current_measurement_settings)
in function main
at projects/power_distribution/src/main.c:153
*********************************************************************
```
Then it calls `__builtin_trap()` to exit immediately (via a hard fault on stm32, or something else like an …

[SOFT-458] Add BUG macro for initialization debuggability

---

libraries/libcore/inc/log.h
libraries/mpxe-store/src/store.c

We previously wouldn't initialize `store` in the MPXE `LOG` implementation. This caused segfaults when using babydriver with MPXE, because it calls `LOG_DEBUG` first thing before any initialization. Fix by calling `store_config()` in `LOG`.

[SOFT-460] Fix logging in MPXE

---

mpxe/harness/pm.py
mpxe/harness/project.py
mpxe/sims/mci.py

You thought regular spaghetti code was bad, try spaghetti concurrency
- MCI handler uses timers instead of blocking the poll thread
- Project gets a ref to PM instead of needing it passed as an arg sometimes
- All writes go through main thread via a queue and spaghetti concurrency

[SOFT-345] Write on main thread, and minor refactoring

---

libraries/ms-helper/src/x86/ads1015.c
mpxe/integration_tests/test_ads1259.py
mpxe/integration_tests/test_adt7476a.py
mpxe/integration_tests/test_leds.py
mpxe/integration_tests/test_mci.py
mpxe/integration_tests/test_pca9539r.py
mpxe/integration_tests/test_pedal.py
projects/smoke_ads1259/src/main.c
projects/smoke_adt7476a/src/main.c
projects/smoke_pca9539r/src/main.c

This adjusts some smoketest timings and driver timings to better accomodate mpxe by making integration tests run faster.
Smoketest timings have super minimal effects because users can always just adjust them manually when using them.
The change in ads1015 is because it was previously a 625 us loop, which caused perf issues with the latest soft_timer library changes and mpxe locking strategy. This is only on the x86 version, where there shouldn't be any necessity to be reading values at that frequency.

[SOFT-233] Adjust timings for MPXE

---

libraries/ms-common/src/x86/gpio.c
libraries/ms-drivers/src/x86/pca9539r_gpio_expander.c
libraries/mu-store/src/store.c
mu/harness/board_sim.py
mu/integration_tests/deps.mk
mu/integration_tests/test_pd_init.py
mu/sims/front_pd.py

- Fix conceptual error in gpio MU: use input_pins correctly
- Fix memory leak in PCA9539r init pin: if already initialized, free the old store and use the new one
- Prevent initializing multiple stores with same key in store.c
- Add test for initializing PD to be the correct one

[SOFT-158] Fix a lot of bugs

---

libraries/libcore/inc/log.h

The MU `LOG` implementation uses a static buffer to store logs to be exported. This was causing issues in PD, where use of the `BUG` macro would cause strings to exceed the 256-byte buffer (and gcc would actually detect this at compile time!).
To fix this, I got rid of the buffer entirely by using [`asprintf`](https://man7.org/linux/man-pages/man3/asprintf.3.html), a GNU extension which works like `snprintf` except it mallocs enough memory for the resulting string automatically. This does mean using the heap, but that's ok on MU since it's only for x86. Plus, we now don't have a `static char s_log_buf[256]` polluting the namespace of every file that includes log.h on MU.

[SOFT-380] Fix buffer overflow in MU logging

---

.github/workflows/main.yml

I typo'd `DEFINES` instead of `DEFINE` when setting up the GitHub Actions CI script. That was causing STM32 builds to build with log-level debug instead of warn as it should be. Thanks @hewittmcg for finding this.

[SOFT-233] Fix typo in CI script

---

libraries/ms-drivers/inc/mcp3427_adc_defs.h
libraries/ms-drivers/src/stm32f0xx/mcp3427_adc.c
libraries/ms-drivers/src/stm32f0xx/spv1020_mppt.c
libraries/ms-drivers/test/test_spv1020_mppt.c
projects/smoke_mcp3427/rules.mk
projects/smoke_mcp3427/src/main.c
projects/smoke_spi/src/main.c
projects/smoke_spv1020/src/main.c
projects/solar/inc/pin_defs.h
projects/solar/rules.mk
projects/solar/src/solar_config.c

These were actually discovered and fixed in like September, for some reason I never put up a PR for them. So here they are.
Changes in order of appearance:
* Increase the max MCP3427 conversion time which we wait before checking for a conversion, because I think it was throwing too many errors.
* Actually assign the sample rate from the settings to the storage in MCP3427, we weren't doing that before and it was defaulting to 16 bits (slowest and most precise).
* Fix an endianness issue in the SPV1020 driver, it turns out the SPV1020 is big-endian while the STM32 is little-endian. Plus, relying on the endianness of the host system is a bad idea anyways.
* Increase the SPI baudrate from 60000 to the 6000000 value we use everywhere else in the SPI and SPV1020 smoketests, plus a few tests and …

[SOFT-167] Fix a bunch of solar validation bugs

---

libraries/ms-common/src/x86/adc.c
libraries/ms-drivers/src/ads1259_adc.c
libraries/ms-drivers/src/adt7476a_fan_controller.c
libraries/ms-helper/src/x86/ads1015.c
libraries/mu-store/src/store.c
mu/ctl/args.py
mu/ctl/req.py
mu/ctl/sims.py
mu/ctl/stores.py
mu/harness/board_sim.py
mu/harness/decoder.py
mu/harness/pm.py
mu/harness/sim_io.py
mu/sims/pedal_board.py
mu/srv/handler.py
mu/srv/server.py

This PR implements viewing and updating stores.
- small improvements:
- make all 'sensor' driver (adc, ads1259, ads1015, adt7476a) actually export their stores, so that when viewing stores you always have a complete picture
- set up CAN in server.py, so if CAN isn't set up yet it'll work out of the box. it'll still fail (could be more graceful but whatever) if you try to run it with not vcan0 and you don't have the network set up.
- make store.c not segfault if the update isn't expected. This could happen if a store isn't initialized and the store is updated. it's kind of an unnecessary check but I still want it because of the new ability to set stores from python.
- req.py returns the request object instead of just the text, so that callers can check the status code. this is why there's …

[SOFT-484] Implement viewing and updating stores

---

projects/mci/inc/mci_fan_control.h
projects/mci/rules.mk
projects/mci/src/main.c
projects/mci/src/mci_fan_control.c
projects/mci/test/test_mci_fan_control.c

Fan control module for MCI.  The way this works is pretty simple -- there's a single pin, `MCI_FAN_EN_ADDR`, that is used to turn on/off the fans.  This is abstracted by `mci_fan_set_state()`.  Hardware wants the fan state based on the temperature measurements from the motor controllers, so that's for a future ticket.
There are also four pins that go high when the corresponding thermistor on the MCI board hits a certain threshold.  Eventually we should log these over CAN using `SYSTEM_CAN_MESSAGE_MOTOR_STATUS`, but for now we just track their status in a fault bitset that can be exported using `mci_fan_get_fault_bitset()`.  A fault callback can also be passed in on initialization, and will be called each time the fault bitset updates.
The test sequence for this is pretty short, as the …

[SOFT-275] MCI Fan Control

---

.github/workflows/make_dbc_release.yml

Creates a release containing the system_can.dbc file under tag [action run #]-[commit id], for every push to master

[SOFT-459] add dbc releaser action

---

projects/smoke_steering/src/main.c
projects/steering/inc/steering_digital_input.h

These are the correct pins according to Aashmika - the pins are mislabelled on the schematic. Also updated smoke_steering to be a bit more consistent with steering itself in terms of naming.

[SOFT-513] Fix steering pins

---

libraries/ms-common/test/test_lights_signal_fsm.c

`test_lights_signal_fsm_sends_sync_msgs` occasionally fails in CI. This attempts to fix that by increasing the buffer between when a blink event should be raised and when we check that it is raised.

[SOFT-536] Fix flaky lights_signal_fsm test

---

.github/workflows/main.yml
libraries/nanopb/LICENSE
libraries/nanopb/README.md

For some reason, the fiam/arm-none-eabi-gcc action in CI was failing with a certificate issue. To fix it, we just install the arm-none-eabi toolchain ourselves instead of using the third-party action.
Also, added a copy of the nanopb license to libraries/nanopb so we don't violate any license terms.

[SOFT-539] Fix CI certificate issue

---

platform/stm32f0xx/platform.mk

Ok I know it's not ideal, but in the original box there's some chef recipe that sets up some rules so that devices can be opened by all users. I couldn't figure it out with backpack, but this is a super simple solution that would improve (mostly just my own) quality of life a lot and is pretty harmless.

[SOFT-233] Sudo openocd

---

projects/smoke_pca9539r/src/main.c

This has caused too much grief to not be corrected.
The schematics for rev 3.0 are unclear, but this is what works in hardware right now.

Correct I2C port in smoke_pca9539r

---

projects/smoke_ads1259/src/main.c

It's just a bit nicer this way.  (The 100* scaling factor is actually an good fix, the read cycle sizes just make more sense this way)

[SOFT-151] Fix scaling in ads1259 smoketest

---

platform/stm32f0xx/platform.mk

We updated the bootloader size from 16K to 32K at some point but neglected to update `make temp-bootloader-write`, which would cause impossible-to-debug linker script issues. Updated the size to fix it.
@mitchellostler, @vaaranan-y, and anyone else testing bootloader onsite this weekend: you'll have to make sure this PR is on your branch before testing. Otherwise, you should be able to do `make temp-bootloader-write PROJECT=leds` to flash the `leds` project on top of the bootloader (although the config will *not* be populated). Also, if you're testing the flash-application-code operation, you might have to dig into the linker scripts to generate a properly offsetted application-only binary (though it *should* just be as simple as using the .bin file for the particular application …

[SOFT-413] Fix sizes in `make temp-bootloader-write`

---

projects/bootloader/scripts/ping.py
projects/bootloader/scripts/test_ping.py
projects/bootloader/scripts/test_ping_all.py

Implement the Python/client side of the bootloader ping operation using the CAN datagram library.
- `test_ping.py` tests ping functionality by passing specific controller board IDs
- `test_ping_all.py` tests ping functionality of pinging all controller boards
To run these tests, you can do something like `python3 test_ping.py`.  Running the tests requires the python `can` libraries and a virtual can interface:
```bash
sudo apt install python3-can # for Python 3.x  
sudo modprobe vcan
sudo ip link add dev vcan0 type vcan
sudo ip link set up vcan0
```

[FWXV-15] Implement client-side Ping operation for CAN bootloader
